-- Auto-generated DDL for UI PR #4
-- Generated by AI Backend-UI Sync Agent
-- Review carefully before applying to production

BEGIN;

ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS address VARCHAR(300) NULL;

COMMIT;
